### ISSUE TITLE
Question: Bulk Update

### ISSUE THREAD

**Issue by iambudi** [SAP/go-hdb#51]
Is there a way to do bulk update just like bulk insert?

**Comment by iambudi** [comment]
Adding BULK keyword just like INSERT in front of UPDATE works. Will update later if no issue.

**Comment by stfnmllr** [comment]
Yes, since one of the last versions 'bulk' is not restricted to insert only. Anyway, documentation was not changed as in general SQL updates do work on sets of records unlike insert, which adds only one record to the DB at one time. Would be great if you can share your use case for which you do need bulk operations for DB updates - thanks in advance.

**Comment by iambudi** [comment]
The use case:

I need to compile sales data from two different data sources into a single table for reporting. 
First source will provide data on daily basis, while the other one on monthly basis (closing period).
So the data stored from first source will be updated massively by data coming from the second source. 

_I consider to put each in seperate tables using `BULK INSERT` and create Join View, but since only few columns to update, i decided to use `BULK UPDATE`._

**Comment by stfnmllr** [comment]
Thanks - I guess the update needs to be done on single records so no mass / set operation by the where clause cannot be used.
Did the 'bulk statement' for update work?
Most probably you use it because of performance considerations. If performance is an issue you might think about a stored procedure solution as well.

**Comment by iambudi** [comment]
Hi @stfnmllr so far the bulk statement for update works nicely. I can close this question issue. Thank you.
