### ISSUE TITLE
Performance issue with go-hdb versions > v0.99.2

### ISSUE THREAD

**Issue by ulranh** [SAP/go-hdb#59]
I'm using go-hdb for the [hana_sql_exporter](https://github.com/ulranh/hana_sql_exporter) to get sap/hana metrics for [prometheus](https://prometheus.io/). With versions up to v0.99.2 a normal scrape with a few hundred selects on different tenants takes about 200ms. With go-hdb versions > v0.99.2 the same scrape takes more than 400ms.

It seems, that since v0.100 a lot of time is spent for crypto algorithms like shown in the following pprof top:

![pprofTop](https://user-images.githubusercontent.com/6552/93088038-b2e4f500-f699-11ea-94b6-b788ace66d50.png)

**Comment by stfnmllr** [comment]
Yes, this is due to a change in user / password authentication. Since 0.100.0 go-hdb does support authentication method SCRAMPBKDF2SHA256 (based on PBKDF2) which is the current hdb server standard for user / password auth. The support was necessary as many hdb server instances are configured to only allow this user / password authentication. Whereas the go-hdb driver supports SCRAMSHA256 as well (used before 0.100.0) the server will choose SCRAMPBKDF2SHA256 in favor of SCRAMSHA256 for all server versions with SCRAMPBKDF2SHA256 capability.
Unfortunately PBKDF2 is a more resource consuming algorithm and the go implementation is not the most efficient one (see https://github.com/golang/go/issues/19941). Alternatives like https://github.com/ctz/go-fastpbkdf2 are CGO based and therefore not an option for go-hdb.
Anyway, the negative performance impact does only occur in establishing a connection. To mitigate the issue you might think about 'long-lived' connections and retrieving data of the different tenants in parallel.
